package net.malta.model.payment;

public interface PaymentConstants {

	public final String PURCHASE_PAYMENT_COMPLETED = "PURCHASE.PAYMENT.COMPLETED";
	public final String PURCHASE_PAYMENT_ACSCONFIRM = "PURCHASE.PAYMENT.ACSCONFIRM";
	public final String PURCHASE_PAYMENTMETHODISBLANK = "PURCHASE.PAYMENT.PAYMENTMETHODISBLANK";
	public final String PURCHASE_PAYMENT_SECUREAUTHENTICATIONFAILED = "PURCHASE.PAYMENT.SECUREAUTHENTICATIONFAILED";
	public final String PURCHASE_PAYMENT_PAYMENTEXECUTION_FAILED ="PURCHASE.PAYMENT.PAYMENTEXECUTIONFAILED";
	public final String ACS_PAYMENTREQUESTS_MISMATCH = "PURCHASE.PAYMENT. ACS_PAYMENTREQUESTS_MISMATCH";
	public final String PURCHASE_PAYMENTMETHODNOTVALID = "PURCHASE.PAYMENT.PAYMENTMETHODNOTVALID";
}
