package net.malta.model.validator.constants;

public interface DeliveryAddressConstants {

	String NAMEISBLANK = "DELIVERYADDRESS.NAMEISBLANK";
	String KANAISBLANK = "DELIVERYADDRESS.KANAISBLANK";
	String ZIPISBLANK = "DELIVERYADDRESS.ZIPISBLANK";
	String PHONEISBLANK = "DELIVERYADDRESS.PHONEISBLANK";
	String PHONEISNOTNUMERIC = "DELIVERYADDRESS.PHONEISNOTNUMERIC";
	String PREFECTUREISBLANK = "DELIVERYADDRESS.PREFECTUREISBLANK";
	String ADDRESSISBLANK = "DELIVERYADDRESS.ADDRESS_ISBLANK";

}
