package net.malta.model.validator.constants;

public interface PublicUserConstants {
	
	public static final String USER_DOESNOTEXIST = "PUBLICUSER.DOESNOTEXIST";
	public static final String USERNAME_ISBLANK = "PUBLICUSER.USERNAMEISBLANK";
	public static final String KANA_ISBLANK = "PUBLICUSER.KANAISBLANK";
	public static final String ZIP_ISBLANK = "PUBLICUSER.ZIPISBLANK";
	public static final String PREFECTURE_ISBLANK = "PUBLICUSER.PREFECTUREISBLANK";
	public static final String EMAIL_ISBLANK = "PUBLICUSER.EMAILISBLANK";
	public static final String ADDRESS_ISBLANK = "PUBLICUSER.ADDRESSISBLANK";
	public static final String FAX_ISBLANK = "PUBLICUSER.FAXISBLANK";
	public static final String FAX_ISNOTNUMERIC = "PUBLICUSER.FAXISNOTNUMERIC";
	public static final String PHONE_ISBLANK = "PUBLICUSER.PHONEISBLANK";
	public static final String CITY_ISBLANK = "PUBLICUSER.CITYISBLANK";
	public static final String AUTHUSERID_ISBLANK = "PUBLICUSER.AUTHUSERIDISBLANK";
	public static final String PREFECTURE_NOTVALID = "PUBLICUSER.PREFECTURENOTVALID";
	public static final String EMAILCONFIRM_ISBLANK = "PUBLICUSER.EMAILFORCONFIRMISBLANK";
	public static final String EMAIL_EMAILCONFIRM_NOTSAME = "PUBLICUSER.EMAIL_EMAILFORCONFIRM_NOTSAME";
	public static final String USER_ALREADYEXISTSWITHTHISEMAIL = "PUBLICUSER.USERALREADYEXISTSWITHTHISEMAIL";
	
}
