ALTER TABLE PRODUCT
ADD COLUMN ENGLISH VARCHAR(255);

ALTER TABLE CHOISE
ADD COLUMN CARRIAGE INT NULL AFTER ITEM_FK;

ALTER TABLE CHOISE
ADD COLUMN NAME VARCHAR(255) BINARY NOT NULL AFTER CARRIAGE;

ALTER TABLE CHOISE
ADD COLUMN VARIETYCHOISE VARCHAR(255) NULL AFTER NAME;

ALTER TABLE CHOISE
ADD COLUMN IMG VARCHAR(255) BINARY NULL AFTER VARIETYCHOISE;

ALTER TABLE CHOISE
ADD COLUMN wp_posts_id INT NULL AFTER IMG;

ALTER TABLE PUBLIC_USER
ADD COLUMN CITY VARCHAR(255) BINARY NULL AFTER BUILDINGNAME;

ALTER TABLE PUBLIC_USER
ADD COLUMN AUTH_USERID INT NULL;

ALTER TABLE DELIVERY_ADDRESS
ADD COLUMN CITY VARCHAR(255) BINARY NULL AFTER BUILDINGNAME;

ALTER TABLE static_data   
  ADD COLUMN `ADMIN_EMAILADDRESSES` VARBINARY(2000) NOT NULL AFTER `CONTRACT_CODE`;