DELETE FROM `attachment`;
ALTER TABLE attachment AUTO_INCREMENT=1;

DELETE FROM `db_file`;
ALTER TABLE db_file AUTO_INCREMENT=1;

DELETE FROM `carriage`;
ALTER TABLE carriage AUTO_INCREMENT=1;

DELETE FROM `category`;
ALTER TABLE category AUTO_INCREMENT=1;

DELETE FROM `gift_card`;
ALTER TABLE gift_card AUTO_INCREMENT=1;

DELETE FROM `item`;
ALTER TABLE item AUTO_INCREMENT=1;

DELETE FROM `product`;
ALTER TABLE product AUTO_INCREMENT=1;

DELETE FROM `payment_method`;
ALTER TABLE payment_method AUTO_INCREMENT=1;

DELETE FROM wp_posts;
ALTER TABLE wp_posts AUTO_INCREMENT=1;

DELETE FROM wp_postmeta;
ALTER TABLE wp_postmeta AUTO_INCREMENT=1;

DELETE FROM `static_data`;
ALTER TABLE static_data AUTO_INCREMENT=1;


DELETE FROM PREFECTURE_CARRIAGE;
ALTER TABLE PREFECTURE_CARRIAGE AUTO_INCREMENT=1;

DELETE FROM PREFECTURE;
ALTER TABLE PREFECTURE AUTO_INCREMENT=1;

DELETE FROM USER_ROLES;
ALTER TABLE USER_ROLES AUTO_INCREMENT=1;

DELETE FROM USER;
ALTER TABLE USER AUTO_INCREMENT=1;

DELETE FROM ROLE;
ALTER TABLE ROLE AUTO_INCREMENT=1;